import Fastify from"fastify";import rateLimit from"@fastify/rate-limit";import{StreamableHTTPServerTransport}from"@modelcontextprotocol/sdk/server/streamableHttp.js";import{SearchRequestSchema,OutcomeEventSchema}from"../contracts/search.js";import{dashboardHtml}from"./dashboard.js";import{createMcpServer}from"../mcp.js";import type{Config}from"../config.js";import type{SearchHarness,EpisodeStore}from"../core/harness.js";import{PostgresStore,type Principal}from"../storage/postgres.js";
export async function makeApp(c:Config,h:SearchHarness,s:EpisodeStore){const app=Fastify({logger:{level:c.LOG_LEVEL},trustProxy:true});await app.register(rateLimit,{max:120,timeWindow:"1 minute"});const db=s instanceof PostgresStore?s:null;app.addHook("preHandler",async(req,reply)=>{if(req.url==="/"||req.url==="/healthz"||req.url==="/metrics"||req.url==="/v1/signup")return;const key=String(req.headers.authorization??"").replace(/^Bearer\s+/i,"");let p:Principal|null=null;if(db)p=await db.authenticate(key);if(!p&&c.apiKeys.has(key))p={tenantId:c.apiKeys.get(key)!,role:"admin",scopes:["*"]};if(!p)return reply.code(401).send({error:"unauthorized"});(req as any).principal=p});
app.get("/healthz",async()=>({status:"ok"}));app.get("/",async(_req,reply)=>reply.type("text/html; charset=utf-8").send(dashboardHtml));
app.post("/v1/signup",async(req,reply)=>{if(!db)return reply.code(503).send({error:"signup_unavailable"});const body=req.body as any;if(!body?.email||!/^[^@]+@[^@]+\.[^@]+$/.test(body.email))return reply.code(400).send({error:"valid_email_required"});try{if(typeof body.password!=="string"||body.password.length<10)return reply.code(400).send({error:"password_min_10"});return reply.code(201).send(await db.signup(body.email,body.password,String(body.display_name??"").slice(0,120)||undefined))}catch(e:any){if(e?.code==="23505")return reply.code(409).send({error:"email_exists"});throw e}});
app.post("/v1/verify-email",async(req,reply)=>db&&await db.verifyEmail(String((req.body as any)?.token??""))?{verified:true}:reply.code(400).send({error:"invalid_or_expired_token"}));app.post("/v1/login",async(req,reply)=>{if(!db)return reply.code(503).send({error:"login_unavailable"});const b=req.body as any;const x=await db.login(String(b?.email??""),String(b?.password??""));return x??reply.code(401).send({error:"invalid_credentials"})});app.get("/v1/providers",async()=>({providers:["tavily","exa","brave","serper","serpapi","google_cse","perplexity","valyu","jina","firecrawl","gemini_deep_research"],configuration:"Availability is reflected in route metadata; credentials are never returned."}));
app.post("/v1/search",async(req,reply)=>{const parsed=SearchRequestSchema.safeParse(req.body);if(!parsed.success)return reply.code(400).send({error:"invalid_request",issues:parsed.error.issues});const p=(req as any).principal as Principal;if(db&&!await db.consume(p))return reply.code(429).send({error:"quota_exceeded"});if(parsed.data.tenant_id!==p.tenantId)return reply.code(403).send({error:"tenant_mismatch"});const r=await h.search({...parsed.data,user_id:p.userId??parsed.data.user_id},{principal:p,surface:"rest"});if(r.status==="needs_input"&&db)await db.savePending({episodeId:r.episode_id,principal:p,request:parsed.data,question:r.question,resumeToken:r.resume_token});return r});app.post("/v1/resume",async(req,reply)=>{if(!db)return reply.code(503).send({error:"resume_unavailable"});const p=(req as any).principal as Principal,b=req.body as any,prior=await db.takePending(String(b?.resume_token??""),p);if(!prior)return reply.code(400).send({error:"invalid_or_expired_resume"});const answer=String(b?.answer??"").slice(0,2000);const resumed=SearchRequestSchema.parse({...prior,context:[...(prior.context??[]),{key:"human_answer",value:answer,source:"human",confidence:1}],permissions:{...prior.permissions,may_ask_user:false}});return h.search(resumed,{principal:p,surface:"resume"})});
app.post("/v1/outcomes",async(req,reply)=>{const p=OutcomeEventSchema.safeParse(req.body);if(!p.success)return reply.code(400).send({error:"invalid_event",issues:p.error.issues});await s.outcome(p.data);return reply.code(202).send({accepted:true})});
app.get("/v1/history",async(req,reply)=>db?db.history((req as any).principal,Math.min(Number((req.query as any)?.limit)||50,100)):reply.code(503).send({error:"history_unavailable"}));
app.get("/v1/usage",async(req,reply)=>db?db.usageSummary((req as any).principal):reply.code(503).send({error:"usage_unavailable"}));
app.all("/mcp",async(req,reply)=>{if(req.method!=="POST")return reply.code(405).send({jsonrpc:"2.0",error:{code:-32000,message:"Method not allowed"},id:null});const server=createMcpServer(h,(req as any).principal);const transport=new StreamableHTTPServerTransport({sessionIdGenerator:undefined,enableJsonResponse:true});await server.connect(transport);reply.hijack();try{await transport.handleRequest(req.raw,reply.raw,req.body)}finally{reply.raw.on("close",()=>{transport.close();server.close()})}});return app}
