export const dashboardHtml = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>divAIne Search | Operations</title><style>
:root{color-scheme:light}*{box-sizing:border-box}body{font:15px/1.5 system-ui,-apple-system,sans-serif;margin:0;background:#f4efec;color:#251f21}main{max-width:1100px;margin:30px auto;padding:30px;background:white;border-radius:22px}header{display:flex;justify-content:space-between;gap:18px;align-items:flex-start;border-bottom:1px solid #eae9ea;padding-bottom:20px}h1{font-size:29px;line-height:1.2;margin:0}h2{font-size:18px;margin:0 0 12px}p{margin:6px 0 16px;color:#585254}section{padding:22px 0;border-bottom:1px solid #eae9ea}label{display:block;font-weight:600;margin:10px 0 5px}input{font:inherit;width:100%;padding:11px;border:1px solid #c0bebf;border-radius:7px}button{font:inherit;border:0;border-radius:7px;background:#167b6a;color:white;padding:10px 14px;cursor:pointer;margin:8px 8px 0 0}button.secondary{background:#585254}pre{white-space:pre-wrap;overflow:auto;background:#faf8f7;padding:16px;border-radius:9px;max-height:440px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}.muted{color:#585254;font-size:13px}a{color:#167b6a}@media(max-width:680px){main{margin:0;border-radius:0;padding:20px}.grid{grid-template-columns:1fr}header{display:block}}</style></head><body><main><header><div><h1>divAIne Search operations</h1><p>Tracking, quality, latency and cost. Search runs through the curated MCP endpoint, not this dashboard.</p></div><button class="secondary" id="clear">Clear local access</button></header>
<section class="grid"><div><h2>Account</h2><label for="email">Email</label><input id="email" type="email" autocomplete="username"><label for="password">Password</label><input id="password" type="password" autocomplete="current-password"><button id="login">Log in</button><p class="muted">New builder accounts use the sign-up API. Keep access tokens outside prompts.</p></div><div><h2>Access</h2><label for="key">Builder key, session token or platform-admin key</label><input id="key" type="password" autocomplete="off"><button id="save">Use this key</button><p class="muted">Key stays in this browser only. Builder views are tenant-scoped; platform-wide usage requires a separate audited role.</p></div></section>
<section><h2>Operations</h2><button id="usage">Usage and estimated cost</button><button id="history">Search history and traces</button><button id="shadow">Shadow routing</button><button id="platform">Platform usage (admin only)</button><button class="secondary" id="export">Export tenant history</button><pre id="output" aria-live="polite">Choose an operations view.</pre></section>
<section><h2>Integration</h2><p>Use the <code>personalized_web_search</code> tool at your configured MCP endpoint. The calling agent supplies its permitted context and handles follow-up questions. The REST search route remains for integrations and evaluation, not dashboard querying.</p></section></main><script>
const $=id=>document.getElementById(id);const output=$('output');$('key').value=sessionStorage.getItem('divaine_ops_key')||'';
const auth=()=>({'authorization':'Bearer '+$('key').value});
async function get(url){output.textContent='Loading...';try{const response=await fetch(url,{headers:auth()});const text=await response.text();let data;try{data=JSON.parse(text)}catch{data=text}output.textContent=JSON.stringify({status:response.status,data},null,2)}catch(e){output.textContent=String(e)}}
$('save').onclick=()=>{sessionStorage.setItem('divaine_ops_key',$('key').value);output.textContent='Key stored for this browser tab.'};
$('clear').onclick=()=>{sessionStorage.removeItem('divaine_ops_key');$('key').value='';output.textContent='Local access cleared.'};
$('login').onclick=async()=>{try{const r=await fetch('/v1/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:$('email').value,password:$('password').value})});const j=await r.json();$('password').value='';if(!r.ok)throw new Error(j.error||'Login failed');$('key').value=j.session_token;sessionStorage.setItem('divaine_ops_key',j.session_token);output.textContent='Signed in. Tenant: '+j.tenant_id}catch(e){output.textContent=String(e)}};
$('usage').onclick=()=>get('/v1/usage');$('history').onclick=()=>get('/v1/history');$('shadow').onclick=()=>get('/v1/admin/shadow');$('platform').onclick=()=>get('/v1/admin/usage');
$('export').onclick=async()=>{try{const r=await fetch('/v1/export',{headers:auth()});if(!r.ok)throw new Error('Export failed: '+r.status);const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='divaine-history.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),5000)}catch(e){output.textContent=String(e)}};
</script></body></html>`;
