import {describe,it,expect} from "vitest";
import {SearchRequestSchema} from "../src/contracts/search.js";
import {curateParameters} from "../src/core/parameter-curation.js";
import {fallbackIntentFormation} from "../src/core/intent-formation.js";
import {validateModelParameters,normalizeQuestions} from "../src/core/architecture.js";
const req=(x:any={})=>SearchRequestSchema.parse({query:"watch for formal dinners",tenant_id:"t",...x});
const manifest=(r:any,parameters:any[])=>validateModelParameters({parameters},r,fallbackIntentFormation(r),curateParameters(r));
describe("model parameter and question safety",()=>{
 const object={key:"search_object",class:"functional",why:"what is sought",query_reference:"watch",weight_percent:30,compulsory:true};
 it("does not promote an ungrounded private motive into a compulsory question",()=>{const r=req();const m=manifest(r,[object,{key:"appearance_context",class:"psychological",why:"occasion preferences",weight_percent:70,compulsory:true,question:"Are you buying this for social validation?"}]);expect(m.parameters.find(p=>p.key==="appearance_context")).toMatchObject({state:"missing",compulsory:false});expect(normalizeQuestions({questions:[{key:"appearance_context",question:"Do you want people to look up to you?"}]},m)).toEqual([])});
 it("refuses invented query values, sensitive psychology and invalid weights",()=>{const r=req();expect(()=>manifest(r,[{...object,query_reference:"not in query",weight_percent:100}])).toThrow(/exact query phrase/);expect(manifest(r,[{...object,weight_percent:50},{key:"religion",class:"psychological",why:"x",weight_percent:50,compulsory:true}]).parameters.map(p=>p.key)).toEqual(["search_object"]);expect(manifest(r,[{...object,weight_percent:99}]).parameters[0]?.priority).toBeCloseTo(100)});
 it("does not let a model use a query phrase to invent a psychological fact",()=>{const r=req();expect(()=>manifest(r,[object,{key:"social_recognition",class:"psychological",why:"possible motive",query_reference:"formal dinners",weight_percent:70,compulsory:true}])).toThrow(/query_reference requires a functional/)});
});
it('preserves original numeric RAM and budget constraints despite a soft or omitted model proposal',()=>{
 const r=req({query:'Best laptop with 16GB RAM for coding under 80000 INR'});
 const ps=[{key:'search_object',class:'functional',why:'object',query_reference:'laptop',weight_percent:70,compulsory:false},{key:'ram',class:'functional',why:'RAM',query_reference:'16GB RAM',weight_percent:30,compulsory:false,hard:false}];
 const m=manifest(r,ps);expect(m.parameters.find(p=>p.key==='ram')).toMatchObject({hard:true,value:'16GB RAM',state:'resolved'});expect(m.parameters.find(p=>p.key==='price_max_inr')).toMatchObject({hard:true,value:80000,state:'resolved'});expect(m.parameters.reduce((n,p)=>n+p.priority,0)).toBeCloseTo(100);
});
it('treats physical battery duration as functional without inventing its value',()=>{const r=req();const m=manifest(r,[{key:'search_object',class:'functional',why:'object',query_reference:'watch',weight_percent:70,compulsory:false},{key:'battery_life_preference',class:'psychological',why:'battery duration',weight_percent:30,compulsory:false}]);expect(m.parameters.find(p=>p.key==='battery_life_preference')).toMatchObject({class:'functional',state:'missing'});expect(m.parameters[0]?.question).toBeUndefined()});
it('classifies a numeric budget as functional even if the model calls it psychology',()=>{const r=req();const m=manifest(r,[{key:'search_object',class:'functional',why:'object',query_reference:'watch',weight_percent:70,compulsory:false},{key:'budget',class:'psychological',why:'max price',weight_percent:30,compulsory:false}]);expect(m.parameters.find(p=>p.key==='budget')).toMatchObject({class:'functional',state:'missing'})});
it('does not make a more detailed coding question compulsory when coding purpose is supplied',()=>{const r=req({query:'Best laptop with 16GB RAM for coding under 80000 INR'});const intent=fallbackIntentFormation(r);intent.answer_unit='product';intent.required_context=[{key:'coding_type',question:'What kind of coding?',why:'workload'}];const base=curateParameters(r,undefined,undefined,intent);expect(base.parameters.find(p=>p.key==='coding_type')?.compulsory).not.toBe(true);});
