import {it,expect} from 'vitest';
import {normalizeDecisionNarrative,applyDecisionNarrative,decisionAnswerPrompt} from '../src/core/decision-answer.js';
import {GeminiMandateWriter} from '../src/core/mandate.js';
import {buildFinalAnswer} from '../src/core/answer.js';
import {SearchRequestSchema,SearchResponseSchema} from '../src/contracts/search.js';
const r=SearchRequestSchema.parse({tenant_id:'t',query:'choose a walkable place'});
const x:any={url:'https://example.com/place',title:'Place A',fields:{walking_path:{state:'supported',value:'2 km trail',evidence:'Place A has a 2 km trail'},price:{state:'missing',value:null}},faithfulness:{state:'supported',score:1}};
const claim={text:'A 2 km trail gives you a concrete walk to plan around.',fact_keys:['walking_path'],preference_keys:[]};
const proposed={options:[{candidate_key:x.url,why:[claim],experience:[claim],tradeoffs:[]}]};
it('adds decision explanations without promoting verification or changing links',()=>{const a=buildFinalAnswer(r,[x],[],[]);const out=applyDecisionNarrative(a,normalizeDecisionNarrative(proposed,r,[x]));expect(out.options[0]?.why[0]).toBe(claim.text);expect(out.options[0]?.experience).toHaveLength(1);expect(out.options[0]?.catch).toEqual(a.options[0]?.catch);expect(out.options[0]?.links).toEqual(a.options[0]?.links);expect(out.status).toBe('provisional_options')});
it('rejects missing facts, invented preferences, URLs and new entities in narratives',()=>{const raw={options:[{candidate_key:x.url,why:[{...claim,fact_keys:['price']},{...claim,preference_keys:['likes_wilderness']},{...claim,text:'Book https://fake.example'}]},{candidate_key:'new',why:[claim]}]};expect(normalizeDecisionNarrative(raw,r,[x])).toEqual([{candidate_key:x.url,why:[],experience:[],tradeoffs:[]}]);expect(decisionAnswerPrompt(r,{intent:r.query} as any,[x])).toContain('Missing evidence stays unknown')});
it('only retains reviewed claims that were actually proposed',async()=>{const w=new GeminiMandateWriter({} as any);let n=0;(w as any).generate=async()=>++n===1?proposed:{options:[{...proposed.options[0],why:[claim,{...claim,text:'Invented extra claim'}]}]};const out=await w.synthesize(r,{intent:r.query} as any,[x]);expect(n).toBe(2);expect(out[0]?.why).toEqual([claim])});
