import{describe,it,expect}from"vitest";import{SearchHarness,MemoryStore}from"../src/core/harness.js";import{HeuristicMandateWriter}from"../src/core/mandate.js";import{SearchRequestSchema}from"../src/contracts/search.js";const c:any={SEARCH_TIMEOUT_MS:1000};const base={query:"best quiet laptop",tenant_id:"t",context:[],permissions:{may_pull_context:false,may_ask_user:false,may_retain:false,may_learn:false,scopes:[]},limits:{latency_ms:1000,max_provider_calls:3,max_results:10}};describe("harness",()=>{it("runs without keys",async()=>{const h=new SearchHarness(c,new HeuristicMandateWriter(),[],new MemoryStore());const r=await h.search(SearchRequestSchema.parse(base));expect(r.status).toBe("complete");if(r.status==="complete")expect(r.limitations[0]).toMatch(/No provider/) });it("keeps mandates internal and never asks the end user",async()=>{const h=new SearchHarness(c,new HeuristicMandateWriter(),[],new MemoryStore());const r=await h.search(SearchRequestSchema.parse({...base,query:"find delivery near me",permissions:{...base.permissions,may_ask_user:true}}));expect(r.status).toBe("complete");expect("mandate" in r).toBe(false);expect("question" in r).toBe(false)})});

describe("contracts",()=>{it("rejects tenantless requests",()=>{expect(SearchRequestSchema.safeParse({query:"x"}).success).toBe(false)});it("does not retain without permission",async()=>{const h=new SearchHarness(c,new HeuristicMandateWriter(),[],new MemoryStore());const r=await h.search(SearchRequestSchema.parse(base));expect(r.status==="complete"&&r.retention_until).toBeUndefined()})});

describe("agent understanding",()=>{it("accepts only typed user-agent psychological context",()=>{const x=SearchRequestSchema.parse({...base,agent_understanding:{source:"user_agent",deliberation_style:"concise",psychological_parameters:[{key:"time_scarcity",value:"high",confidence:.9,evidence:[{source:"caller",reference:"agent profile"}]}]}});expect(x.agent_understanding?.source).toBe("user_agent")});it("rejects any other source company",()=>{expect(SearchRequestSchema.safeParse({...base,agent_understanding:{source:"simulation",deliberation_style:"concise",psychological_parameters:[]}}).success).toBe(false)})});

describe("one question",()=>{it("asks once when allowed and a material gap has a question, then never when not allowed",async()=>{const w:any={write:async()=>({id:"00000000-0000-4000-8000-000000000000",version:2,prompt_version:"t",intent:"x",category:"x",factors:[],gaps:[{key:"budget",material:true,question:"What is your budget?"}]})};const h=new SearchHarness(c,w,[],new MemoryStore());let asked=0;h.ask=async()=>{asked++;return{resume_token:"dvr_x"}};const r:any=await h.search(SearchRequestSchema.parse({...base,permissions:{...base.permissions,may_ask_user:true}}));expect(r.status).toBe("needs_input");expect(r.question).toBe("What is your budget?");const r2:any=await h.search(SearchRequestSchema.parse(base));expect(r2.status).toBe("complete");expect(asked).toBe(1)})});

import { SearchHarness as _SH } from "../src/core/harness.js";
import { HeuristicMandateWriter as _HW } from "../src/core/mandate.js";
import { SearchRequestSchema as _SRS } from "../src/contracts/search.js";
import { it as _it, expect as _ex } from "vitest";
_it("a storage failure never fails the search", async () => {
  const store: any = { save: async () => { throw new Error("fk violation"); } };
  const h = new _SH({ SEARCH_TIMEOUT_MS: 1000 } as any, new _HW(), [{ name: "exa", enabled: () => true, search: async () => [{ provider: "exa", url: "https://a.example.com/1", title: "t", snippet: "s" }] } as any], store, { fetcher: (async () => ({ ok: false })) as any });
  const out: any = await h.search(_SRS.parse({ tenant_id: "production", query: "test query" }));
  _ex(out.status).toBe("complete"); _ex(out.limitations.join(" ")).toMatch(/not recorded/);
});
