import {it,expect,vi,afterEach} from 'vitest';
const mock=vi.hoisted(()=>({answers:{} as any,calls:0}));
vi.mock('@typesafe-ai/sdk',()=>({choice:(question:string,options:any)=>({question,options}),TypeSafeClient:class{async systemOne(){mock.calls++;return{model:'test',answers:mock.answers}}}}));
import {routeSubqueries} from '../src/core/jev-router.js';import {SearchRequestSchema} from '../src/contracts/search.js';import {HeuristicMandateWriter} from '../src/core/mandate.js';import {executePlan,planJobs,ProviderHealth} from '../src/core/jobs.js';
afterEach(()=>{delete process.env.TYPESAFE_API_KEY;mock.calls=0});
const jobs=[{id:'discovery',query:'research batteries',candidates:[{provider:'exa'},{provider:'tavily'},{provider:'serper',excluded:'not eligible'}]}];
const answer=(count:string,names:string[])=>({count_0:{choice:count,confidence:.9},...Object.fromEntries(names.map((choice,i)=>[`provider_0_${i}`,{choice,confidence:.9}]))});
async function route(cap=3){process.env.TYPESAFE_API_KEY='test';const r=SearchRequestSchema.parse({tenant_id:'t',query:'research batteries',limits:{max_provider_calls:cap}});return routeSubqueries(r,await new HeuristicMandateWriter().write(r),jobs)}
it('model chooses one or two rather than exhausting ceiling',async()=>{mock.answers=answer('1',['exa']);expect((await route())[0].providers).toEqual(['exa']);mock.answers=answer('2',['tavily','exa']);expect((await route())[0].providers).toEqual(['tavily','exa'])});
it('invalid counts, excluded choices and duplicates remain explicit fallback',async()=>{for(const a of [answer('8',['exa']),answer('2',['exa','exa']),answer('1',['serper'])]){mock.answers=a;expect((await route())[0]).toMatchObject({policy:'capability-v1'});expect((await route())[0].providers).toBeUndefined()}});
it('global ceiling clamps multiple valid job choices',async()=>{process.env.TYPESAFE_API_KEY='test';const r=SearchRequestSchema.parse({tenant_id:'t',query:'research batteries',limits:{max_provider_calls:2}});mock.answers={...answer('2',['exa','tavily']),count_1:{choice:'2',confidence:.9},provider_1_0:{choice:'exa',confidence:.9},provider_1_1:{choice:'tavily',confidence:.9}};const out=await routeSubqueries(r,await new HeuristicMandateWriter().write(r),[...jobs,{...jobs[0],id:'second'}]);expect(out.flatMap(d=>d.providers??[])).toHaveLength(2);expect(out[1].providers).toEqual([])});
it('execution fires every chosen provider and no hidden grade-based extras',async()=>{const r=SearchRequestSchema.parse({tenant_id:'t',query:'research batteries',limits:{max_provider_calls:3}});const providers=['exa','tavily','serper'].map(name=>({name,enabled:()=>true,search:async()=>[]}));const p=planJobs(r,await new HeuristicMandateWriter().write(r),providers);p.jobs[0].selected_providers=['exa','tavily'];const called:string[]=[];await executePlan(p,providers,async(x)=>{called.push(x.name);return{status:'ok',latency_ms:1,results:[]}},()=>0,new ProviderHealth());expect(called).toEqual(['exa','tavily'])});
