import {it,expect} from 'vitest';import {namedProductQuery} from '../src/core/product-repair.js';import {productFields} from '../src/core/product-fields.js';
it('builds named follow-up only from retrieved title, preserving original requirements',()=>{const q=namedProductQuery([{provider:'serper',url:'https://google.com/search?q=x',title:'Acer Aspire Lite 16 GB RAM AL15-41',snippet:''}],'laptop coding under 80000 INR');expect(q).toContain('Acer Aspire Lite');expect(q).toContain('under 80000 INR');expect(namedProductQuery([{provider:'tavily',url:'https://x.com',title:'Best laptops',snippet:''}],'laptop')).toBeUndefined()});
it('verifies unique labelled INR offer and explicit RAM, never first random currency or capacity',()=>{expect(productFields('Price: ₹64,999\n16 GB RAM')).toMatchObject({product_price_inr:{value:64999,state:'supported'},ram_gb:{value:16,state:'supported'}});expect(productFields('MRP ₹80,000\nShipping ₹50\n512GB SSD')).toMatchObject({product_price_inr:{state:'missing'},ram_gb:{state:'missing'}});expect(productFields('Price ₹60,000\nPrice ₹65,000\n8 GB RAM or 16 GB RAM')).toMatchObject({product_price_inr:{state:'missing'},ram_gb:{state:'missing'}});expect(productFields('Up to 32 GB RAM')).toMatchObject({ram_gb:{state:'missing'}})});
import {SearchHarness,MemoryStore} from '../src/core/harness.js';import {HeuristicMandateWriter} from '../src/core/mandate.js';import {SearchRequestSchema} from '../src/contracts/search.js';
it('named-model web resolution counts as one visible repair within the global ceiling',async()=>{
 const calls:any[]=[];const p={name:'serper',enabled:()=>true,search:async(c:any)=>{calls.push(c);return c.search_vertical==='web'?[{provider:'serper',url:'https://shop.example.com/product/acer',title:'Acer Aspire Lite 16 GB RAM',snippet:'Price: ₹64,999. 16 GB RAM'}]:[{provider:'serper',url:'https://google.com/search?q=laptop',title:'Acer Aspire Lite 16 GB RAM',snippet:'₹64,999'}]}};
 const h=new SearchHarness({SEARCH_TIMEOUT_MS:1000} as any,new HeuristicMandateWriter(),[p],new MemoryStore(),{fetcher:async()=>({ok:true,text:async()=> 'Acer Aspire Lite 16 GB RAM\nPrice: ₹64,999\n16 GB RAM'}) as any});
 const out:any=await h.search(SearchRequestSchema.parse({query:'laptop with 16GB RAM for coding under 80000 INR',tenant_id:'t',limits:{max_provider_calls:2,max_jobs:1}}));expect(calls.length).toBe(2);expect(calls[1].search_vertical).toBe('web');expect(calls[1].request.query).toContain('Acer Aspire Lite');expect(out.results[0].url).toContain('/product/acer');expect(out.results[0].verification.price.status).toBe('verified');expect(out.route.length).toBe(2);
});
