import {HttpProvider,type ProviderContext,type SearchProvider} from "./base.js";import{CircuitProvider}from"./circuit.js";import{splitGroundedAnswer}from"../core/faithfulness.js";import type{ProviderResult}from"../contracts/search.js";const legacyQ=(c:ProviderContext)=>[c.request.query,...c.mandate.factors.filter(f=>f.hard&&f.value!=null).map(f=>`${f.key}:${String(f.value)}`)].join(" ");import{buildQueryPlan,exaParams,serpApiParams,valyuParams,jinaParams,firecrawlParams}from"./query-plan.js";
export class Tavily extends HttpProvider{name="tavily";enabled=()=>!!process.env.TAVILY_API_KEY;async search(c:ProviderContext){const d=await this.json("https://api.tavily.com/search",{method:"POST",headers:{"content-type":"application/json",Authorization:`Bearer ${process.env.TAVILY_API_KEY?.trim()}`},body:JSON.stringify({query:legacyQ(c),max_results:c.request.limits.max_results})},c.signal);return (d.results??[]).map((x:any)=>({provider:this.name,url:x.url,title:x.title,snippet:x.content??"",score:x.score}))}}
export class Exa extends HttpProvider{name="exa";enabled=()=>!!process.env.EXA_API_KEY;async search(c:ProviderContext){const d=await this.json("https://api.exa.ai/search",{method:"POST",headers:{"content-type":"application/json","x-api-key":process.env.EXA_API_KEY!},body:JSON.stringify(exaParams(buildQueryPlan(c.request,c.mandate)))},c.signal);return (d.results??[]).map((x:any)=>({provider:this.name,url:x.url,title:x.title??x.url,snippet:x.text??"",score:x.score}))}}
export class Brave extends HttpProvider{name="brave";enabled=()=>!!process.env.BRAVE_API_KEY;async search(c:ProviderContext){const u=new URL("https://api.search.brave.com/res/v1/web/search");u.searchParams.set("q",legacyQ(c));u.searchParams.set("count",String(c.request.limits.max_results));const d=await this.json(u.href,{headers:{Accept:"application/json","X-Subscription-Token":process.env.BRAVE_API_KEY!}},c.signal);return (d.web?.results??[]).map((x:any)=>({provider:this.name,url:x.url,title:x.title,snippet:x.description??""}))}}
export class Serper extends HttpProvider{name="serper";enabled=()=>!!process.env.SERPER_API_KEY;async search(c:ProviderContext){const d=await this.json("https://google.serper.dev/search",{method:"POST",headers:{"content-type":"application/json","X-API-KEY":process.env.SERPER_API_KEY!.trim()},body:JSON.stringify({q:legacyQ(c),num:c.request.limits.max_results})},c.signal);return (d.organic??[]).map((x:any)=>({provider:this.name,url:x.link,title:x.title,snippet:x.snippet??""}))}}
export class SerpApi extends HttpProvider{name="serpapi";enabled=()=>!!process.env.SERPAPI_API_KEY;async search(c:ProviderContext){const u=new URL("https://serpapi.com/search.json");for(const[k,v]of Object.entries(serpApiParams(buildQueryPlan(c.request,c.mandate))))u.searchParams.set(k,String(v));u.searchParams.set("api_key",process.env.SERPAPI_API_KEY!);const d=await this.json(u.href,{},c.signal);return (d.organic_results??[]).map((x:any)=>({provider:this.name,url:x.link,title:x.title,snippet:x.snippet??""}))}}
export class GoogleCse extends HttpProvider{name="google_cse";enabled=()=>!!process.env.GOOGLE_CSE_API_KEY&&!!process.env.GOOGLE_CSE_ID;async search(c:ProviderContext){const u=new URL("https://www.googleapis.com/customsearch/v1");u.searchParams.set("q",legacyQ(c));u.searchParams.set("key",process.env.GOOGLE_CSE_API_KEY!.trim());u.searchParams.set("cx",process.env.GOOGLE_CSE_ID!);const d=await this.json(u.href,{},c.signal);return (d.items??[]).map((x:any)=>({provider:this.name,url:x.link,title:x.title,snippet:x.snippet??""}))}}
export class Perplexity extends HttpProvider{name="perplexity";enabled=()=>!!process.env.PERPLEXITY_API_KEY;async search(c:ProviderContext){const d=await this.json("https://api.perplexity.ai/chat/completions",{method:"POST",headers:{"content-type":"application/json",Authorization:`Bearer ${process.env.PERPLEXITY_API_KEY?.trim()}`},body:JSON.stringify({model:"sonar",messages:[{role:"user",content:legacyQ(c)}]})},c.signal);return splitGroundedAnswer(this.name,d.choices?.[0]?.message?.content??"",d.citations??[])}}


export class Valyu extends HttpProvider{name="valyu";enabled=()=>!!process.env.VALYU_API_KEY;async search(c:ProviderContext){const d=await this.json("https://api.valyu.ai/v1/search",{method:"POST",headers:{"content-type":"application/json","x-api-key":process.env.VALYU_API_KEY!},body:JSON.stringify(valyuParams(buildQueryPlan(c.request,c.mandate)))},c.signal);const rows=Array.isArray(d.results)?d.results:Array.isArray(d.data)?d.data:[];return rows.map((x:any)=>({provider:this.name,url:x.url,title:x.title??x.url,snippet:x.content??x.snippet??x.description??"",score:x.relevance_score??x.score}))}}
export class JinaReader extends HttpProvider{name="jina";enabled=()=>!!process.env.JINA_API_KEY;async search(c:ProviderContext){const plan=jinaParams(buildQueryPlan(c.request,c.mandate)),url="https://s.jina.ai/"+encodeURIComponent(plan.query);const d=await fetch(url,{headers:{Accept:"application/json",Authorization:`Bearer ${process.env.JINA_API_KEY}`},signal:c.signal});if(!d.ok)throw new Error(`jina HTTP ${d.status}`);const x:any=await d.json();const rows=x.data??x.results??[];return rows.slice(0,c.request.limits.max_results).map((r:any)=>({provider:this.name,url:r.url,title:r.title??r.url,snippet:r.description??r.content??""}))}}
export class Firecrawl extends HttpProvider{name="firecrawl";enabled=()=>!!process.env.FIRECRAWL_API_KEY;async search(c:ProviderContext){const d=await this.json("https://api.firecrawl.dev/v2/search",{method:"POST",headers:{"content-type":"application/json",Authorization:`Bearer ${process.env.FIRECRAWL_API_KEY}`},body:JSON.stringify(firecrawlParams(buildQueryPlan(c.request,c.mandate)))},c.signal);const rows=Array.isArray(d.data)?d.data:Array.isArray(d.data?.web)?d.data.web:Array.isArray(d.data?.results)?d.data.results:[];return rows.map((x:any)=>({provider:this.name,url:x.url,title:x.title??x.url,snippet:x.description??x.markdown?.slice(0,1500)??""}))}}
export class GeminiDeepResearch implements SearchProvider{name="gemini_deep_research";enabled=()=>!!process.env.GEMINI_API_KEY;async search(_:ProviderContext):Promise<ProviderResult[]>{return []}}
export function allProviders():SearchProvider[]{return[new Tavily(),new Exa(),new SerpApi(),new Valyu(),new JinaReader(),new Firecrawl()].map(p=>new CircuitProvider(p))}
