import {HttpProvider,type ProviderContext,type SearchProvider} from "./base.js";import type{ProviderResult}from"../contracts/search.js";
const q=(c:ProviderContext)=>[c.request.query,...c.mandate.factors.filter(f=>f.hard&&f.value!=null).map(f=>`${f.key}:${String(f.value)}`)].join(" ");
export class Tavily extends HttpProvider{name="tavily";enabled=()=>!!process.env.TAVILY_API_KEY;async search(c:ProviderContext){const d=await this.json("https://api.tavily.com/search",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({api_key:process.env.TAVILY_API_KEY,query:q(c),max_results:c.request.limits.max_results})},c.signal);return (d.results??[]).map((x:any)=>({provider:this.name,url:x.url,title:x.title,snippet:x.content??"",score:x.score}))}}
export class Exa extends HttpProvider{name="exa";enabled=()=>!!process.env.EXA_API_KEY;async search(c:ProviderContext){const d=await this.json("https://api.exa.ai/search",{method:"POST",headers:{"content-type":"application/json","x-api-key":process.env.EXA_API_KEY!},body:JSON.stringify({query:q(c),numResults:c.request.limits.max_results,contents:{text:{maxCharacters:1500}}})},c.signal);return (d.results??[]).map((x:any)=>({provider:this.name,url:x.url,title:x.title??x.url,snippet:x.text??"",score:x.score}))}}
export class Brave extends HttpProvider{name="brave";enabled=()=>!!process.env.BRAVE_API_KEY;async search(c:ProviderContext){const u=new URL("https://api.search.brave.com/res/v1/web/search");u.searchParams.set("q",q(c));u.searchParams.set("count",String(c.request.limits.max_results));const d=await this.json(u.href,{headers:{Accept:"application/json","X-Subscription-Token":process.env.BRAVE_API_KEY!}},c.signal);return (d.web?.results??[]).map((x:any)=>({provider:this.name,url:x.url,title:x.title,snippet:x.description??""}))}}
export class Serper extends HttpProvider{name="serper";enabled=()=>!!process.env.SERPER_API_KEY;async search(c:ProviderContext){const d=await this.json("https://google.serper.dev/search",{method:"POST",headers:{"content-type":"application/json","X-API-KEY":process.env.SERPER_API_KEY!},body:JSON.stringify({q:q(c),num:c.request.limits.max_results})},c.signal);return (d.organic??[]).map((x:any)=>({provider:this.name,url:x.link,title:x.title,snippet:x.snippet??""}))}}
export class SerpApi extends HttpProvider{name="serpapi";enabled=()=>!!process.env.SERPAPI_API_KEY;async search(c:ProviderContext){const u=new URL("https://serpapi.com/search.json");u.searchParams.set("q",q(c));u.searchParams.set("api_key",process.env.SERPAPI_API_KEY!);u.searchParams.set("num",String(c.request.limits.max_results));const d=await this.json(u.href,{},c.signal);return (d.organic_results??[]).map((x:any)=>({provider:this.name,url:x.link,title:x.title,snippet:x.snippet??""}))}}
export class GoogleCse extends HttpProvider{name="google_cse";enabled=()=>!!process.env.GOOGLE_CSE_API_KEY&&!!process.env.GOOGLE_CSE_ID;async search(c:ProviderContext){const u=new URL("https://www.googleapis.com/customsearch/v1");u.searchParams.set("q",q(c));u.searchParams.set("key",process.env.GOOGLE_CSE_API_KEY!);u.searchParams.set("cx",process.env.GOOGLE_CSE_ID!);const d=await this.json(u.href,{},c.signal);return (d.items??[]).map((x:any)=>({provider:this.name,url:x.link,title:x.title,snippet:x.snippet??""}))}}
export class Perplexity extends HttpProvider{name="perplexity";enabled=()=>!!process.env.PERPLEXITY_API_KEY;async search(c:ProviderContext){const d=await this.json("https://api.perplexity.ai/chat/completions",{method:"POST",headers:{"content-type":"application/json",Authorization:`Bearer ${process.env.PERPLEXITY_API_KEY}`},body:JSON.stringify({model:"sonar",messages:[{role:"user",content:q(c)}]})},c.signal);const cites=d.citations??[];return cites.map((url:string,i:number)=>({provider:this.name,url,title:`Perplexity source ${i+1}`,snippet:d.choices?.[0]?.message?.content??""}))}}
export class GeminiDeepResearch implements SearchProvider{name="gemini_deep_research";enabled=()=>!!process.env.GEMINI_API_KEY;async search(_:ProviderContext):Promise<ProviderResult[]>{return []}}
export function allProviders():SearchProvider[]{return[new Tavily(),new Exa(),new Brave(),new Serper(),new SerpApi(),new GoogleCse(),new Perplexity(),new GeminiDeepResearch()]}
