import{createHash,randomBytes,randomUUID,timingSafeEqual}from"node:crypto";import pg from"pg";import type{EpisodeStore}from"../core/harness.js";
export type Principal={tenantId:string,userId?:string,keyId?:string,role:"user"|"admin",scopes:string[]};
const hash=(s:string)=>createHash("sha256").update(s).digest("hex");
export class PostgresStore implements EpisodeStore{private pool:pg.Pool;constructor(url:string){this.pool=new pg.Pool({connectionString:url,max:10,application_name:"divaine-search"})}
async migrate(){for(const f of ["migrations/0001_core.sql","migrations/0002_identity_usage.sql"]){const{readFile}=await import("node:fs/promises");await this.pool.query(await readFile(f,"utf8"))}}
async signup(email:string,displayName?:string){const client=await this.pool.connect();try{await client.query("BEGIN");const tenantId=randomUUID(),userId=randomUUID(),keyId=randomUUID(),secret=`dv_${randomBytes(24).toString("base64url")}`,prefix=secret.slice(0,11);await client.query("INSERT INTO tenants(id,name) VALUES($1,$2)",[tenantId,displayName||email.split("@")[0]]);await client.query("INSERT INTO users(id,tenant_id,email,display_name) VALUES($1,$2,$3,$4)",[userId,tenantId,email.toLowerCase(),displayName]);await client.query("INSERT INTO api_keys(id,tenant_id,user_id,prefix,secret_hash) VALUES($1,$2,$3,$4,$5)",[keyId,tenantId,userId,prefix,hash(secret)]);await client.query("COMMIT");return{tenant_id:tenantId,user_id:userId,api_key_id:keyId,api_key:secret,quota_daily:100}}catch(e){await client.query("ROLLBACK");throw e}finally{client.release()}}
async authenticate(secret:string):Promise<Principal|null>{if(!secret.startsWith("dv_"))return null;const r=await this.pool.query("SELECT k.id key_id,k.tenant_id,k.user_id,k.secret_hash,k.scopes,u.role FROM api_keys k JOIN users u ON u.id=k.user_id WHERE k.prefix=$1 AND k.revoked_at IS NULL AND (k.expires_at IS NULL OR k.expires_at>now())",[secret.slice(0,11)]);for(const x of r.rows){const a=Buffer.from(x.secret_hash),b=Buffer.from(hash(secret));if(a.length===b.length&&timingSafeEqual(a,b))return{tenantId:x.tenant_id,userId:x.user_id,keyId:x.key_id,role:x.role,scopes:x.scopes}}return null}
async save(x:any){const started=x.startedAt??Date.now();await this.pool.query("INSERT INTO episodes(id,tenant_id,user_id,session_id,request,response,expires_at,api_key_id,duration_ms) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(id) DO NOTHING",[x.id,x.tenantId,x.principal?.userId??x.request.user_id,x.request.session_id,x.request,x.response,x.expiresAt,x.principal?.keyId,Date.now()-started]);const route=x.response?.status==="complete"?x.response.route:[];if(!route.length)await this.usage(x,null,0,Date.now()-started);for(const p of route)await this.usage(x,p.provider,p.result_count,p.latency_ms)}
private async usage(x:any,provider:string|null,resultCount:number,duration:number){await this.pool.query("INSERT INTO usage_events(id,tenant_id,user_id,api_key_id,episode_id,surface,provider,result_count,duration_ms) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)",[randomUUID(),x.tenantId,x.principal?.userId??x.request.user_id,x.principal?.keyId,x.id,x.surface??"rest",provider,resultCount,duration])}
async outcome(x:any){await this.pool.query("INSERT INTO outcomes(id,episode_id,payload) VALUES($1,$2,$3)",[x.event_id??randomUUID(),x.episode_id,x])}
async history(p:Principal,limit=50){return(await this.pool.query("SELECT id,request->>'query' query,response,created_at,duration_ms FROM episodes WHERE tenant_id=$1 AND ($2::uuid IS NULL OR user_id=$2) ORDER BY created_at DESC LIMIT $3",[p.tenantId,p.role==='admin'?null:p.userId,limit])).rows}
async usageSummary(p:Principal){return(await this.pool.query("SELECT user_id,provider,count(*)::int calls,sum(result_count)::int results,round(sum(estimated_cost_usd),6) cost_usd,round(avg(duration_ms))::int avg_latency_ms FROM usage_events WHERE tenant_id=$1 AND ($2::uuid IS NULL OR user_id=$2) AND created_at>now()-interval '30 days' GROUP BY user_id,provider ORDER BY calls DESC",[p.tenantId,p.role==='admin'?null:p.userId])).rows}
async purgeExpired(){return(await this.pool.query("DELETE FROM episodes WHERE expires_at < now() RETURNING id")).rowCount??0}async close(){await this.pool.end()}}
