import{createHash,randomBytes,randomUUID,timingSafeEqual}from"node:crypto";import{hash as argonHash,verify as argonVerify}from"argon2";import pg from"pg";import type{EpisodeStore}from"../core/harness.js";
const UUID_RE=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;export const isUuid=(x:unknown)=>typeof x==="string"&&UUID_RE.test(x);
export type Principal={tenantId:string,userId?:string,keyId?:string,role:"user"|"admin",scopes:string[]};const sha=(s:string)=>createHash("sha256").update(s).digest("hex");
// Static API keys carry a name-style tenant ("production"). Requests must match the principal's
// tenant, so only static keys reach here with a non-UUID tenant. Map it to a stable UUID and a
// tenants row so its episodes and usage are stored like any account tenant.
export const staticTenantId=(name:string)=>{const h=createHash("sha256").update("static-tenant:"+name).digest("hex");return`${h.slice(0,8)}-${h.slice(8,12)}-4${h.slice(13,16)}-8${h.slice(17,20)}-${h.slice(20,32)}`};
export class PostgresStore implements EpisodeStore{private pool:pg.Pool;private staticSeen=new Set<string>();private async tid(t:string){if(isUuid(t))return t;const id=staticTenantId(t);if(!this.staticSeen.has(id)){await this.pool.query("INSERT INTO tenants(id,name) VALUES($1,$2) ON CONFLICT(id) DO NOTHING",[id,"static:"+t.slice(0,100)]);this.staticSeen.add(id)}return id}constructor(url:string){this.pool=new pg.Pool({connectionString:url,max:10,application_name:"divaine-search"})}async migrate(){const{readFile}=await import("node:fs/promises");for(const f of ["migrations/0001_core.sql","migrations/0002_identity_usage.sql","migrations/0003_resume.sql","migrations/0004_mandate_v2.sql","migrations/0005_learning.sql"])await this.pool.query(await readFile(f,"utf8"))}
async signup(email:string,password:string,displayName?:string){const client=await this.pool.connect();try{await client.query("BEGIN");const tenantId=randomUUID(),userId=randomUUID(),keyId=randomUUID(),secret=`dv_${randomBytes(24).toString("base64url")}`,verifyToken=randomBytes(24).toString("base64url");await client.query("INSERT INTO tenants(id,name) VALUES($1,$2)",[tenantId,displayName||email.split("@")[0]]);await client.query("INSERT INTO users(id,tenant_id,email,display_name,password_hash) VALUES($1,$2,$3,$4,$5)",[userId,tenantId,email.toLowerCase(),displayName,await argonHash(password)]);await client.query("INSERT INTO api_keys(id,tenant_id,user_id,prefix,secret_hash) VALUES($1,$2,$3,$4,$5)",[keyId,tenantId,userId,secret.slice(0,11),sha(secret)]);await client.query("INSERT INTO verification_tokens(id,user_id,token_hash,expires_at) VALUES($1,$2,$3,now()+interval '24 hours')",[randomUUID(),userId,sha(verifyToken)]);await client.query("COMMIT");return{tenant_id:tenantId,user_id:userId,api_key_id:keyId,api_key:secret,quota_daily:100,verification_token:verifyToken}}catch(e){await client.query("ROLLBACK");throw e}finally{client.release()}}
async verifyEmail(token:string){const r=await this.pool.query("UPDATE users u SET verified_at=now() FROM verification_tokens v WHERE v.user_id=u.id AND v.token_hash=$1 AND v.used_at IS NULL AND v.expires_at>now() RETURNING u.id",[sha(token)]);if(r.rowCount)await this.pool.query("UPDATE verification_tokens SET used_at=now() WHERE token_hash=$1",[sha(token)]);return!!r.rowCount}
async login(email:string,password:string){const r=await this.pool.query("SELECT id,tenant_id,password_hash,role FROM users WHERE email=$1",[email.toLowerCase()]);const u=r.rows[0];if(!u?.password_hash||!await argonVerify(u.password_hash,password))return null;const token=`dvs_${randomBytes(24).toString("base64url")}`;await this.pool.query("INSERT INTO sessions(id,user_id,token_hash,expires_at) VALUES($1,$2,$3,now()+interval '7 days')",[randomUUID(),u.id,sha(token)]);return{session_token:token,expires_in:604800,tenant_id:u.tenant_id,user_id:u.id,role:u.role}}
async authenticate(secret:string):Promise<Principal|null>{if(secret.startsWith("dvs_")){const r=await this.pool.query("SELECT u.id user_id,u.tenant_id,u.role FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=$1 AND s.expires_at>now()",[sha(secret)]);const x=r.rows[0];return x?{tenantId:x.tenant_id,userId:x.user_id,role:x.role,scopes:["dashboard","search","mcp"]}:null}if(!secret.startsWith("dv_"))return null;const r=await this.pool.query("SELECT k.id key_id,k.tenant_id,k.user_id,k.secret_hash,k.scopes,k.quota_daily,k.used_today,k.usage_day,u.role FROM api_keys k JOIN users u ON u.id=k.user_id WHERE k.prefix=$1 AND k.revoked_at IS NULL AND (k.expires_at IS NULL OR k.expires_at>now())",[secret.slice(0,11)]);for(const x of r.rows){const a=Buffer.from(x.secret_hash),b=Buffer.from(sha(secret));if(a.length===b.length&&timingSafeEqual(a,b)){if(String(x.usage_day)!==new Date().toISOString().slice(0,10))await this.pool.query("UPDATE api_keys SET used_today=0,usage_day=current_date WHERE id=$1",[x.key_id]);return{tenantId:x.tenant_id,userId:x.user_id,keyId:x.key_id,role:x.role,scopes:x.scopes}}}return null}
async consume(p:Principal){if(!p.keyId)return true;const r=await this.pool.query("UPDATE api_keys SET used_today=used_today+1 WHERE id=$1 AND (usage_day<current_date OR used_today<quota_daily) RETURNING id",[p.keyId]);return!!r.rowCount}
async save(x:any){const tenantId=await this.tid(String(x.tenantId));const uid=x.principal?.userId;const started=x.startedAt??Date.now();await this.pool.query("INSERT INTO episodes(id,tenant_id,user_id,session_id,request,response,mandate,expires_at,api_key_id,duration_ms) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT(id) DO NOTHING",[x.id,tenantId,uid??x.request.user_id,x.request.session_id,x.request,x.response,x.mandate,x.expiresAt,x.principal?.keyId,Date.now()-started]);for(const p of x.response?.route??[])await this.pool.query("INSERT INTO usage_events(id,tenant_id,user_id,api_key_id,episode_id,surface,provider,result_count,duration_ms,estimated_cost_usd) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)",[randomUUID(),tenantId,uid??null,x.principal?.keyId??null,x.id,x.surface??"rest",p.provider,p.result_count,p.latency_ms,providerCost(p.provider)])}
async savePending(x:any){if(!isUuid(x.principal?.tenantId))throw new Error("pending_requires_account_tenant");await this.pool.query("INSERT INTO pending_searches(episode_id,tenant_id,user_id,api_key_id,request,question,resume_hash,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,now()+interval '24 hours') ON CONFLICT(episode_id) DO UPDATE SET request=excluded.request,question=excluded.question,resume_hash=excluded.resume_hash",[x.episodeId,x.principal.tenantId,x.principal.userId,x.principal.keyId,x.request,x.question,sha(x.resumeToken)])}async takePending(token:string,p:Principal){const r=await this.pool.query("UPDATE pending_searches SET resumed_at=now() WHERE resume_hash=$1 AND tenant_id=$2 AND resumed_at IS NULL AND expires_at>now() RETURNING request",[sha(token),p.tenantId]);return r.rows[0]?.request??null}
async outcome(x:any){await this.pool.query("INSERT INTO outcomes(id,episode_id,payload) VALUES($1,$2,$3)",[x.event_id??randomUUID(),x.episode_id,x])}async history(p:Principal,limit=50){const t=await this.tid(p.tenantId);return(await this.pool.query("SELECT id,request->>'query' query,response,created_at,duration_ms FROM episodes WHERE tenant_id=$1 AND ($2::text IS NULL OR user_id=$2::text) ORDER BY created_at DESC LIMIT $3",[t,p.role==='admin'?null:p.userId,limit])).rows}async usageSummary(p:Principal){const t=await this.tid(p.tenantId);return(await this.pool.query("SELECT user_id,provider,count(*)::int calls,sum(result_count)::int results,round(sum(estimated_cost_usd),6) cost_usd,round(avg(duration_ms))::int avg_latency_ms FROM usage_events WHERE tenant_id=$1 AND ($2::uuid IS NULL OR user_id=$2) AND created_at>now()-interval '30 days' GROUP BY user_id,provider ORDER BY calls DESC",[t,p.role==='admin'?null:p.userId])).rows}async adminUsage(p:Principal){if(p.role!=="admin")return null;return(await this.pool.query("SELECT t.name tenant,u.email,user_id,provider,count(*)::int calls,sum(result_count)::int results,round(sum(estimated_cost_usd),6) cost_usd,round(avg(duration_ms))::int avg_latency_ms FROM usage_events e JOIN tenants t ON t.id=e.tenant_id LEFT JOIN users u ON u.id=e.user_id WHERE e.created_at>now()-interval '30 days' GROUP BY t.name,u.email,user_id,provider ORDER BY cost_usd DESC,calls DESC")).rows}
async purgeExpired(){return(await this.pool.query("DELETE FROM episodes WHERE expires_at<now() RETURNING id")).rowCount??0}async close(){await this.pool.end()}}
const providerCost=(p:string)=>({exa:.005,tavily:.008,serper:.001,serpapi:.015,valyu:.01,jina:.002,firecrawl:.01,perplexity:.005,google_cse:.005}[p]??0);
